### ISSUE TITLE
RD_KAFKA_PARTITION_UA value

### ISSUE THREAD

**Issue by takaomag** [dfdeshom/nimrdkafka#1]
In rdkafka.h,

``` c
#define RD_KAFKA_PARTITION_UA  ((int32_t)-1)
```

But in rdkafka.nim,

``` nim
RD_KAFKA_PARTITION_UA* =  2_147_483_647
```

I think it is wrong. It should be,

``` nim
RD_KAFKA_PARTITION_UA* : int32 =  -1
```

**Comment by dfdeshom** [comment]
You're right, I haven't kept up with this wrapper as much as I wanted to. Patches welcome!
